package it.unibo.pps.smartgh.model.city

import org.json4s.*
import org.json4s.jackson.JsonMethods.*
import requests.Response
/** This trait exposes methods for managing the selected city, represents its model. */
trait City:
  /** Data structure that will contains the city's environment values. */
  type EnvironmentValues = Map[String, Any]

  /** @return city's name. */
  def name: String

  /** @return
    *   city's environment values for the current day, example of returned value:
   {
    "location": {
        "name": "Rome",
        "region": "Lazio",
        "country": "Italy",
        "lat": 41.9,
        "lon": 12.48,
        "tz_id": "Europe/Rome",
        "localtime_epoch": 1659507400,
        "localtime": "2022-08-03 8:16"
    },
    "current": {
        "last_updated_epoch": 1659507300,
        "last_updated": "2022-08-03 08:15",
        "temp_c": 25.0,
        "temp_f": 77.0,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
        },
        "wind_mph": 2.2,
        "wind_kph": 3.6,
        "wind_degree": 23,
        "wind_dir": "NNE",
        "pressure_mb": 1014.0,
        "pressure_in": 29.94,
        "precip_mm": 0.0,
        "precip_in": 0.0,
        "humidity": 61,
        "cloud": 0,
        "feelslike_c": 25.5,
        "feelslike_f": 77.9,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 7.0,
        "gust_mph": 6.7,
        "gust_kph": 10.8
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2022-08-03",
                "date_epoch": 1659484800,
                "day": {
                    "maxtemp_c": 35.6,
                    "maxtemp_f": 96.1,
                    "mintemp_c": 22.0,
                    "mintemp_f": 71.6,
                    "avgtemp_c": 28.2,
                    "avgtemp_f": 82.8,
                    "maxwind_mph": 13.6,
                    "maxwind_kph": 22.0,
                    "totalprecip_mm": 0.0,
                    "totalprecip_in": 0.0,
                    "avgvis_km": 10.0,
                    "avgvis_miles": 6.0,
                    "avghumidity": 43.0,
                    "daily_will_it_rain": 0,
                    "daily_chance_of_rain": 0,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "uv": 7.0
                },
                "astro": {
                    "sunrise": "06:05 AM",
                    "sunset": "08:26 PM",
                    "moonrise": "11:39 AM",
                    "moonset": "11:21 PM",
                    "moon_phase": "Waxing Crescent",
                    "moon_illumination": "37"
                },
                "hour": [
                    {
                        "time_epoch": 1659477600,
                        "time": "2022-08-03 00:00",
                        "temp_c": 24.3,
                        "temp_f": 75.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.9,
                        "wind_kph": 7.9,
                        "wind_degree": 19,
                        "wind_dir": "NNE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.95,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 51,
                        "cloud": 13,
                        "feelslike_c": 25.4,
                        "feelslike_f": 77.7,
                        "windchill_c": 24.3,
                        "windchill_f": 75.7,
                        "heatindex_c": 25.4,
                        "heatindex_f": 77.7,
                        "dewpoint_c": 13.4,
                        "dewpoint_f": 56.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.1,
                        "gust_kph": 16.2,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1659481200,
                        "time": "2022-08-03 01:00",
                        "temp_c": 24.0,
                        "temp_f": 75.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.7,
                        "wind_kph": 7.6,
                        "wind_degree": 19,
                        "wind_dir": "NNE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.94,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 50,
                        "cloud": 12,
                        "feelslike_c": 25.2,
                        "feelslike_f": 77.4,
                        "windchill_c": 24.0,
                        "windchill_f": 75.2,
                        "heatindex_c": 25.2,
                        "heatindex_f": 77.4,
                        "dewpoint_c": 13.0,
                        "dewpoint_f": 55.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.6,
                        "gust_kph": 15.5,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1659484800,
                        "time": "2022-08-03 02:00",
                        "temp_c": 23.4,
                        "temp_f": 74.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.9,
                        "wind_kph": 7.9,
                        "wind_degree": 11,
                        "wind_dir": "NNE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.94,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 51,
                        "cloud": 8,
                        "feelslike_c": 24.9,
                        "feelslike_f": 76.8,
                        "windchill_c": 23.4,
                        "windchill_f": 74.1,
                        "heatindex_c": 24.9,
                        "heatindex_f": 76.8,
                        "dewpoint_c": 12.8,
                        "dewpoint_f": 55.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.3,
                        "gust_kph": 16.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1659488400,
                        "time": "2022-08-03 03:00",
                        "temp_c": 22.8,
                        "temp_f": 73.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 5.6,
                        "wind_kph": 9.0,
                        "wind_degree": 6,
                        "wind_dir": "N",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.93,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 52,
                        "cloud": 6,
                        "feelslike_c": 24.7,
                        "feelslike_f": 76.5,
                        "windchill_c": 22.8,
                        "windchill_f": 73.0,
                        "heatindex_c": 24.7,
                        "heatindex_f": 76.5,
                        "dewpoint_c": 12.5,
                        "dewpoint_f": 54.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.6,
                        "gust_kph": 18.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1659492000,
                        "time": "2022-08-03 04:00",
                        "temp_c": 22.4,
                        "temp_f": 72.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 5.8,
                        "wind_kph": 9.4,
                        "wind_degree": 10,
                        "wind_dir": "N",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.93,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 54,
                        "cloud": 5,
                        "feelslike_c": 24.6,
                        "feelslike_f": 76.3,
                        "windchill_c": 22.4,
                        "windchill_f": 72.3,
                        "heatindex_c": 24.6,
                        "heatindex_f": 76.3,
                        "dewpoint_c": 12.5,
                        "dewpoint_f": 54.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.1,
                        "gust_kph": 19.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1659495600,
                        "time": "2022-08-03 05:00",
                        "temp_c": 22.0,
                        "temp_f": 71.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 5.8,
                        "wind_kph": 9.4,
                        "wind_degree": 14,
                        "wind_dir": "NNE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.93,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 54,
                        "cloud": 4,
                        "feelslike_c": 24.5,
                        "feelslike_f": 76.1,
                        "windchill_c": 22.0,
                        "windchill_f": 71.6,
                        "heatindex_c": 24.5,
                        "heatindex_f": 76.1,
                        "dewpoint_c": 12.3,
                        "dewpoint_f": 54.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.3,
                        "gust_kph": 19.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1659499200,
                        "time": "2022-08-03 06:00",
                        "temp_c": 23.0,
                        "temp_f": 73.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 5.6,
                        "wind_kph": 9.0,
                        "wind_degree": 18,
                        "wind_dir": "NNE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.95,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 51,
                        "cloud": 4,
                        "feelslike_c": 24.8,
                        "feelslike_f": 76.6,
                        "windchill_c": 23.0,
                        "windchill_f": 73.4,
                        "heatindex_c": 24.8,
                        "heatindex_f": 76.6,
                        "dewpoint_c": 12.4,
                        "dewpoint_f": 54.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.3,
                        "gust_kph": 16.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1659502800,
                        "time": "2022-08-03 07:00",
                        "temp_c": 26.1,
                        "temp_f": 79.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 5.4,
                        "wind_kph": 8.6,
                        "wind_degree": 23,
                        "wind_dir": "NNE",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.96,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 43,
                        "cloud": 5,
                        "feelslike_c": 26.3,
                        "feelslike_f": 79.3,
                        "windchill_c": 26.1,
                        "windchill_f": 79.0,
                        "heatindex_c": 26.3,
                        "heatindex_f": 79.3,
                        "dewpoint_c": 12.4,
                        "dewpoint_f": 54.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.7,
                        "gust_kph": 10.8,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1659506400,
                        "time": "2022-08-03 08:00",
                        "temp_c": 28.9,
                        "temp_f": 84.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.8,
                        "wind_kph": 6.1,
                        "wind_degree": 24,
                        "wind_dir": "NNE",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.97,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 35,
                        "cloud": 7,
                        "feelslike_c": 28.3,
                        "feelslike_f": 82.9,
                        "windchill_c": 28.9,
                        "windchill_f": 84.0,
                        "heatindex_c": 28.3,
                        "heatindex_f": 82.9,
                        "dewpoint_c": 12.0,
                        "dewpoint_f": 53.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.5,
                        "gust_kph": 7.2,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1659510000,
                        "time": "2022-08-03 09:00",
                        "temp_c": 31.6,
                        "temp_f": 88.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 1.6,
                        "wind_kph": 2.5,
                        "wind_degree": 23,
                        "wind_dir": "NNE",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.97,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 30,
                        "cloud": 9,
                        "feelslike_c": 30.7,
                        "feelslike_f": 87.3,
                        "windchill_c": 31.6,
                        "windchill_f": 88.9,
                        "heatindex_c": 30.7,
                        "heatindex_f": 87.3,
                        "dewpoint_c": 11.7,
                        "dewpoint_f": 53.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 1.8,
                        "gust_kph": 2.9,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1659513600,
                        "time": "2022-08-03 10:00",
                        "temp_c": 34.0,
                        "temp_f": 93.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 0.9,
                        "wind_kph": 1.4,
                        "wind_degree": 208,
                        "wind_dir": "SSW",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.96,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 26,
                        "cloud": 10,
                        "feelslike_c": 33.0,
                        "feelslike_f": 91.4,
                        "windchill_c": 34.0,
                        "windchill_f": 93.2,
                        "heatindex_c": 33.0,
                        "heatindex_f": 91.4,
                        "dewpoint_c": 11.6,
                        "dewpoint_f": 52.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 1.1,
                        "gust_kph": 1.8,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1659517200,
                        "time": "2022-08-03 11:00",
                        "temp_c": 33.0,
                        "temp_f": 91.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.4,
                        "wind_kph": 5.4,
                        "wind_degree": 202,
                        "wind_dir": "SSW",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.95,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 24,
                        "cloud": 9,
                        "feelslike_c": 31.4,
                        "feelslike_f": 88.5,
                        "windchill_c": 33.0,
                        "windchill_f": 91.4,
                        "heatindex_c": 31.4,
                        "heatindex_f": 88.5,
                        "dewpoint_c": 9.6,
                        "dewpoint_f": 49.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.3,
                        "gust_kph": 6.8,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1659520800,
                        "time": "2022-08-03 12:00",
                        "temp_c": 33.9,
                        "temp_f": 93.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 7.2,
                        "wind_kph": 11.5,
                        "wind_degree": 209,
                        "wind_dir": "SSW",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.93,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 23,
                        "cloud": 14,
                        "feelslike_c": 32.4,
                        "feelslike_f": 90.3,
                        "windchill_c": 33.9,
                        "windchill_f": 93.0,
                        "heatindex_c": 32.4,
                        "heatindex_f": 90.3,
                        "dewpoint_c": 10.0,
                        "dewpoint_f": 50.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.9,
                        "gust_kph": 14.4,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1659524400,
                        "time": "2022-08-03 13:00",
                        "temp_c": 35.6,
                        "temp_f": 96.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 11.9,
                        "wind_kph": 19.1,
                        "wind_degree": 224,
                        "wind_dir": "SW",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.92,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 24,
                        "cloud": 18,
                        "feelslike_c": 34.9,
                        "feelslike_f": 94.8,
                        "windchill_c": 35.6,
                        "windchill_f": 96.1,
                        "heatindex_c": 34.9,
                        "heatindex_f": 94.8,
                        "dewpoint_c": 12.2,
                        "dewpoint_f": 54.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.6,
                        "gust_kph": 22.0,
                        "uv": 9.0
                    },
                    {
                        "time_epoch": 1659528000,
                        "time": "2022-08-03 14:00",
                        "temp_c": 33.1,
                        "temp_f": 91.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 13.6,
                        "wind_kph": 22.0,
                        "wind_degree": 246,
                        "wind_dir": "WSW",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.92,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 28,
                        "cloud": 13,
                        "feelslike_c": 32.3,
                        "feelslike_f": 90.1,
                        "windchill_c": 33.1,
                        "windchill_f": 91.6,
                        "heatindex_c": 32.3,
                        "heatindex_f": 90.1,
                        "dewpoint_c": 12.2,
                        "dewpoint_f": 54.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 16.6,
                        "gust_kph": 26.6,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1659531600,
                        "time": "2022-08-03 15:00",
                        "temp_c": 32.0,
                        "temp_f": 89.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 13.0,
                        "wind_kph": 20.9,
                        "wind_degree": 251,
                        "wind_dir": "WSW",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.92,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 31,
                        "cloud": 9,
                        "feelslike_c": 31.4,
                        "feelslike_f": 88.5,
                        "windchill_c": 32.0,
                        "windchill_f": 89.6,
                        "heatindex_c": 31.4,
                        "heatindex_f": 88.5,
                        "dewpoint_c": 13.0,
                        "dewpoint_f": 55.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 16.1,
                        "gust_kph": 25.9,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1659535200,
                        "time": "2022-08-03 16:00",
                        "temp_c": 30.9,
                        "temp_f": 87.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 11.2,
                        "wind_kph": 18.0,
                        "wind_degree": 256,
                        "wind_dir": "WSW",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.93,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 37,
                        "cloud": 11,
                        "feelslike_c": 30.8,
                        "feelslike_f": 87.4,
                        "windchill_c": 30.9,
                        "windchill_f": 87.6,
                        "heatindex_c": 30.8,
                        "heatindex_f": 87.4,
                        "dewpoint_c": 14.4,
                        "dewpoint_f": 57.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.9,
                        "gust_kph": 22.3,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1659538800,
                        "time": "2022-08-03 17:00",
                        "temp_c": 31.2,
                        "temp_f": 88.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.1,
                        "wind_kph": 13.0,
                        "wind_degree": 260,
                        "wind_dir": "W",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.93,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 37,
                        "cloud": 15,
                        "feelslike_c": 31.2,
                        "feelslike_f": 88.2,
                        "windchill_c": 31.2,
                        "windchill_f": 88.2,
                        "heatindex_c": 31.2,
                        "heatindex_f": 88.2,
                        "dewpoint_c": 14.7,
                        "dewpoint_f": 58.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.4,
                        "gust_kph": 15.1,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1659542400,
                        "time": "2022-08-03 18:00",
                        "temp_c": 30.8,
                        "temp_f": 87.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 250,
                        "wind_dir": "WSW",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.93,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 39,
                        "cloud": 15,
                        "feelslike_c": 31.0,
                        "feelslike_f": 87.8,
                        "windchill_c": 30.8,
                        "windchill_f": 87.4,
                        "heatindex_c": 31.0,
                        "heatindex_f": 87.8,
                        "dewpoint_c": 15.3,
                        "dewpoint_f": 59.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.8,
                        "gust_kph": 12.6,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1659546000,
                        "time": "2022-08-03 19:00",
                        "temp_c": 29.4,
                        "temp_f": 84.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 5.8,
                        "wind_kph": 9.4,
                        "wind_degree": 250,
                        "wind_dir": "WSW",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.93,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 46,
                        "cloud": 13,
                        "feelslike_c": 30.1,
                        "feelslike_f": 86.2,
                        "windchill_c": 29.4,
                        "windchill_f": 84.9,
                        "heatindex_c": 30.1,
                        "heatindex_f": 86.2,
                        "dewpoint_c": 16.5,
                        "dewpoint_f": 61.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.1,
                        "gust_kph": 13.0,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1659549600,
                        "time": "2022-08-03 20:00",
                        "temp_c": 27.1,
                        "temp_f": 80.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.9,
                        "wind_kph": 7.9,
                        "wind_degree": 265,
                        "wind_dir": "W",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.94,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 56,
                        "cloud": 12,
                        "feelslike_c": 28.2,
                        "feelslike_f": 82.8,
                        "windchill_c": 27.1,
                        "windchill_f": 80.8,
                        "heatindex_c": 28.2,
                        "heatindex_f": 82.8,
                        "dewpoint_c": 17.6,
                        "dewpoint_f": 63.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.7,
                        "gust_kph": 14.0,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1659553200,
                        "time": "2022-08-03 21:00",
                        "temp_c": 26.3,
                        "temp_f": 79.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.1,
                        "wind_kph": 5.0,
                        "wind_degree": 279,
                        "wind_dir": "W",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.96,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 60,
                        "cloud": 12,
                        "feelslike_c": 27.5,
                        "feelslike_f": 81.5,
                        "windchill_c": 26.3,
                        "windchill_f": 79.3,
                        "heatindex_c": 27.5,
                        "heatindex_f": 81.5,
                        "dewpoint_c": 17.8,
                        "dewpoint_f": 64.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.8,
                        "gust_kph": 9.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1659556800,
                        "time": "2022-08-03 22:00",
                        "temp_c": 25.7,
                        "temp_f": 78.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 2.5,
                        "wind_kph": 4.0,
                        "wind_degree": 288,
                        "wind_dir": "WNW",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.96,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 61,
                        "cloud": 10,
                        "feelslike_c": 26.9,
                        "feelslike_f": 80.4,
                        "windchill_c": 25.7,
                        "windchill_f": 78.3,
                        "heatindex_c": 26.9,
                        "heatindex_f": 80.4,
                        "dewpoint_c": 17.6,
                        "dewpoint_f": 63.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.9,
                        "gust_kph": 7.9,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1659560400,
                        "time": "2022-08-03 23:00",
                        "temp_c": 25.3,
                        "temp_f": 77.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 2.9,
                        "wind_kph": 4.7,
                        "wind_degree": 305,
                        "wind_dir": "NW",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.97,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 61,
                        "cloud": 11,
                        "feelslike_c": 26.5,
                        "feelslike_f": 79.7,
                        "windchill_c": 25.3,
                        "windchill_f": 77.5,
                        "heatindex_c": 26.5,
                        "heatindex_f": 79.7,
                        "dewpoint_c": 17.3,
                        "dewpoint_f": 63.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.8,
                        "gust_kph": 9.4,
                        "uv": 1.0
                    }
                ]
            }
        ]
    }
}
    */
  def currentEnvironmentValues: EnvironmentValues

  /** Get the 4 environmental values (temp_c, humidity, condition, uv) according to a specific hour of the day.
    * @param hour in for which environmental values are requested.
    * @return the main city environment values. Output example:
    *         HashMap(uv -> Some(1.0), temp_c -> Some(24.3), time -> Some(2022-08-03 00:00), condition -> Some(Clear), humidity -> Some(51))
    * */
  def mainEnvironmentValues(hour: Int): EnvironmentValues

/** Object that can be use for managing the selected city, represents its model. */
object City:
  /** Apply method for the [[City]].
    * @return
    *   the [[City]] object.
    */
  def apply(name: String): City = CityImpl(name)

  private class CityImpl(override val name: String) extends City:

    private val forecast : EnvironmentValues = getForecast()("forecast").asInstanceOf[Map[String, Any]]

    override def currentEnvironmentValues: EnvironmentValues = mainEnvironmentValues(0)

    override def mainEnvironmentValues(hour: Int): EnvironmentValues =
      val h = if hour < 10 then "0" + hour + ":00" else hour.toString + ":00"
      //val forecast: Map[String, Any] = environmentValues("forecast").asInstanceOf[Map[String, Any]]
      val hours: List[Map[String, Any]] = forecast("forecastday").asInstanceOf[List[Map[String, Any]]].
        foldLeft(forecast("forecastday").asInstanceOf[List[Map[String, Any]]])((m, acc) =>
          acc("hour").asInstanceOf[List[Map[String, Any]]]
        )
      val ch = hours.find(m => m("time").asInstanceOf[String].contains(h))
      Map("time" -> ch.get("time"),
        "temp_c" -> ch.get("temp_c"),
        "uv" -> ch.get("uv"),
        "humidity" -> ch.get("humidity"),
        "condition" -> ch.get("condition").asInstanceOf[Map[String, Any]].get("text").fold("Not available")(res => res.toString))

    private def getForecast(): EnvironmentValues =
      val apiKey = "b619d3592d8b426e8cc92336220107"
      val query =
        "http://api.weatherapi.com/v1/forecast.json?key=" + apiKey + "&q=" + name.replace(" ", "%20") + "&days=1&aqi=no&alerts=no"
      val r: Response = requests.get(query)
      if r.statusCode == 200 then
        implicit val formats = org.json4s.DefaultFormats
        parse(r.text()).extract[EnvironmentValues]
      else Map()