name: test workflow
on:
  push:
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin 
          java-version: 11
      - name: Run test
        run: cd smart_greenhouse/ ; sbt -v +test
