name: test workflow
on:
  push:
  workflow_dispatch:
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-18.04 ]
        java: [ adopt@1.11, adopt@1.16 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - name: Run test
        run: sbt -v -Dfile.encoding=UTF-8 +test
        working-directory: ./smart_greenhouse
